title: Kate Brady
author: kbrady
email: katherine.a.brady@vanderbilt.edu
description: > # this means to ignore newlines until "baseurl:"
  I am a graduate student at Vanderbilt University studying how 
  electronic tools can be used in education.
twitter_username: spacemonkeyhat
github_username:  kbrady

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - stimuli.md

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock